/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/spotahome/service-level-operator/pkg/apis/monitoring/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeServiceLevels implements ServiceLevelInterface
type FakeServiceLevels struct {
	Fake *FakeMonitoringV1alpha1
	ns   string
}

var servicelevelsResource = schema.GroupVersionResource{Group: "monitoring.spotahome.com", Version: "v1alpha1", Resource: "servicelevels"}

var servicelevelsKind = schema.GroupVersionKind{Group: "monitoring.spotahome.com", Version: "v1alpha1", Kind: "ServiceLevel"}

// Get takes name of the serviceLevel, and returns the corresponding serviceLevel object, and an error if there is any.
func (c *FakeServiceLevels) Get(name string, options v1.GetOptions) (result *v1alpha1.ServiceLevel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(servicelevelsResource, c.ns, name), &v1alpha1.ServiceLevel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceLevel), err
}

// List takes label and field selectors, and returns the list of ServiceLevels that match those selectors.
func (c *FakeServiceLevels) List(opts v1.ListOptions) (result *v1alpha1.ServiceLevelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(servicelevelsResource, servicelevelsKind, c.ns, opts), &v1alpha1.ServiceLevelList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ServiceLevelList{}
	for _, item := range obj.(*v1alpha1.ServiceLevelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested serviceLevels.
func (c *FakeServiceLevels) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(servicelevelsResource, c.ns, opts))

}

// Create takes the representation of a serviceLevel and creates it.  Returns the server's representation of the serviceLevel, and an error, if there is any.
func (c *FakeServiceLevels) Create(serviceLevel *v1alpha1.ServiceLevel) (result *v1alpha1.ServiceLevel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(servicelevelsResource, c.ns, serviceLevel), &v1alpha1.ServiceLevel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceLevel), err
}

// Update takes the representation of a serviceLevel and updates it. Returns the server's representation of the serviceLevel, and an error, if there is any.
func (c *FakeServiceLevels) Update(serviceLevel *v1alpha1.ServiceLevel) (result *v1alpha1.ServiceLevel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(servicelevelsResource, c.ns, serviceLevel), &v1alpha1.ServiceLevel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceLevel), err
}

// Delete takes name of the serviceLevel and deletes it. Returns an error if one occurs.
func (c *FakeServiceLevels) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(servicelevelsResource, c.ns, name), &v1alpha1.ServiceLevel{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServiceLevels) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(servicelevelsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ServiceLevelList{})
	return err
}

// Patch applies the patch and returns the patched serviceLevel.
func (c *FakeServiceLevels) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ServiceLevel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(servicelevelsResource, c.ns, name, data, subresources...), &v1alpha1.ServiceLevel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceLevel), err
}
