/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/slok/service-level-operator/pkg/apis/measure/v1alpha1"
	scheme "github.com/slok/service-level-operator/pkg/k8sautogen/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ServiceLevelsGetter has a method to return a ServiceLevelInterface.
// A group's client should implement this interface.
type ServiceLevelsGetter interface {
	ServiceLevels(namespace string) ServiceLevelInterface
}

// ServiceLevelInterface has methods to work with ServiceLevel resources.
type ServiceLevelInterface interface {
	Create(*v1alpha1.ServiceLevel) (*v1alpha1.ServiceLevel, error)
	Update(*v1alpha1.ServiceLevel) (*v1alpha1.ServiceLevel, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ServiceLevel, error)
	List(opts v1.ListOptions) (*v1alpha1.ServiceLevelList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ServiceLevel, err error)
	ServiceLevelExpansion
}

// serviceLevels implements ServiceLevelInterface
type serviceLevels struct {
	client rest.Interface
	ns     string
}

// newServiceLevels returns a ServiceLevels
func newServiceLevels(c *MeasureV1alpha1Client, namespace string) *serviceLevels {
	return &serviceLevels{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the serviceLevel, and returns the corresponding serviceLevel object, and an error if there is any.
func (c *serviceLevels) Get(name string, options v1.GetOptions) (result *v1alpha1.ServiceLevel, err error) {
	result = &v1alpha1.ServiceLevel{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("servicelevels").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ServiceLevels that match those selectors.
func (c *serviceLevels) List(opts v1.ListOptions) (result *v1alpha1.ServiceLevelList, err error) {
	result = &v1alpha1.ServiceLevelList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("servicelevels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested serviceLevels.
func (c *serviceLevels) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("servicelevels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a serviceLevel and creates it.  Returns the server's representation of the serviceLevel, and an error, if there is any.
func (c *serviceLevels) Create(serviceLevel *v1alpha1.ServiceLevel) (result *v1alpha1.ServiceLevel, err error) {
	result = &v1alpha1.ServiceLevel{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("servicelevels").
		Body(serviceLevel).
		Do().
		Into(result)
	return
}

// Update takes the representation of a serviceLevel and updates it. Returns the server's representation of the serviceLevel, and an error, if there is any.
func (c *serviceLevels) Update(serviceLevel *v1alpha1.ServiceLevel) (result *v1alpha1.ServiceLevel, err error) {
	result = &v1alpha1.ServiceLevel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("servicelevels").
		Name(serviceLevel.Name).
		Body(serviceLevel).
		Do().
		Into(result)
	return
}

// Delete takes name of the serviceLevel and deletes it. Returns an error if one occurs.
func (c *serviceLevels) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("servicelevels").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *serviceLevels) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("servicelevels").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched serviceLevel.
func (c *serviceLevels) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ServiceLevel, err error) {
	result = &v1alpha1.ServiceLevel{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("servicelevels").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
