// Code generated by mockery v1.0.0. DO NOT EDIT.

package slo

import mock "github.com/stretchr/testify/mock"
import sli "github.com/slok/service-level-operator/pkg/service/sli"

import v1alpha1 "github.com/slok/service-level-operator/pkg/apis/measure/v1alpha1"

// Output is an autogenerated mock type for the Output type
type Output struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, result
func (_m *Output) Create(_a0 *v1alpha1.SLO, result *sli.Result) error {
	ret := _m.Called(_a0, result)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.SLO, *sli.Result) error); ok {
		r0 = rf(_a0, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
